---
title: Transform-tools
hero_image: images/banner.png
description: Gebruik de Unity Transform-tools om GameObjects te verplaatsen, draaien en schalen
version: 4
listed: false
copyedit: false
last_tested: "2021-11-17"
steps:
  - title: Transform-tools

